---
- hosts: all
  tasks:
    - block:
        - ansible.builtin.apt:
            update_cache: yes
            name: "*"
            state: latest

        # - ansible.builtin.apt:
        #     pkg:
        #       - dotnet-sdk-5.0

        - ansible.builtin.apt:
            autoremove: yes
            autoclean: yes

      become: yes

    - ansible.builtin.get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: "{{ ansible_env.HOME }}/dotnet-install.sh"
        mode: 0750

    - ansible.builtin.command: >-
        {{ ansible_env.HOME }}/dotnet-install.sh
        --channel {{ item }}
        --no-path
      loop:
        - Current
        - LTS

    - ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          export DOTNET_ROOT=$HOME/.dotnet
          export PATH=$PATH:$DOTNET_ROOT
        marker: "# {mark} ANSIBLE MANAGED BLOCK - dotnet"
        insertafter: EOF
        create: yes
