name: Universal Windows Platform (UWP)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Restore the application
        run: msbuild Sensorclock.sln /t:Restore /p:Configuration=$env:Configuration
        working-directory: ./software/cs/uwp
        env:
          Configuration: ${{ matrix.configuration }}
